#ifndef GUARD_CONSTANTS_MUGSHOTS_H
#define GUARD_CONSTANTS_MUGSHOTS_H

// Rank Insignia
#define MUGSHOT_WHITEBAND 0
#define MUGSHOT_REDGEM 1
#define MUGSHOT_ORANGEGEM 2
#define MUGSHOT_YELLOWGEM 3
#define MUGSHOT_GREENGEM 4
#define MUGSHOT_BLUEGEM 5
#define MUGSHOT_INDIGOGEM 6
#define MUGSHOT_VIOLETGEM 7
#define MUGSHOT_GOLDRING 8

#endif
