#ifndef GUARD_CONSTANTS_MUGSHOTS_H
#define GUARD_CONSTANTS_MUGSHOTS_H

// Rank Insignia
#define MUGSHOT_WHITEBAND 0
#define MUGSHOT_REDGEM 1
#define MUGSHOT_ORANGEGEM 2
#define MUGSHOT_YELLOWGEM 3
#define MUGSHOT_GREENGEM 4
#define MUGSHOT_BLUEGEM 5
#define MUGSHOT_INDIGOGEM 6
#define MUGSHOT_VIOLETGEM 7
#define MUGSHOT_GOLDRING 8
#define MUGSHOT_BWEXPERIMENT1 9
#define MUGSHOT_BWEXPERIMENT2 10
#define MUGSHOT_SMEXPERIMENT1 11
#define MUGSHOT_SMEXPERIMENT3 12
#define MUGSHOT_TUTORIAL_SET_IN_GAME_CLOCK 13
#define MUGSHOT_TUTORIAL_STARTER_ABILITIES_1 14
#define MUGSHOT_TUTORIAL_STARTER_ABILITIES_2_GROOKEY 15
#define MUGSHOT_TUTORIAL_STARTER_ABILITIES_2_SOBBLE 16
#define MUGSHOT_TUTORIAL_STARTER_ABILITIES_2_SCORBUNNY 17
#define MUGSHOT_TUTORIAL_BALL_RESTRICTIONS_1 18
#define MUGSHOT_TUTORIAL_BALL_RESTRICTIONS_2 19

#endif
