gText_Birch_Welcome::
	.string "Hello. It's a pleasure to speak to you\nat last.\p"
	.string "My name is {COLOR GREEN}Professor Magnolia{COLOR DARK_GRAY}.\pI'm currently heading up research here\n"
	.string "at {COLOR RED}Unova's Amnesty Institute{COLOR DARK_GRAY}.\p"
	.string "Together, we battle against the forces\nthat have invaded our world.\p"
	.string "Perhaps you're already aware...\p"
	.string "{COLOR RED}Team Rainbow Rocket {COLOR DARK_GRAY}now has\nstrongholds in nine regions, and\l"
	.string "only we remain to oppose them.\p"
	.string "However!\pWhile they have their “secret weapon”,\nin the form of {COLOR RED}Ultra Wormholes{COLOR DARK_GRAY}...\p$"

gText_Birch_Pokemon::
	.string "This is what we call a “POKéMON.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "But I'm getting ahead of myself.\p$"

gText_Birch_AndYouAre::
	.string "Now, these old eyes don't work as well\nas they used to. So tell me...\p$"

gText_Birch_BoyOrGirl::
	.string "Are you a boy, or a girl?$"

gText_Birch_WhatsYourName::
	.string "Very well. And what's your name?$"

gText_Birch_SoItsPlayer::
	.string "“{COLOR GREEN}{PLAYER}{COLOR DARK_GRAY}”...\ndid I get that right?$"

gText_Birch_YourePlayer::
	.string "Well, {COLOR GREEN}{PLAYER}{COLOR DARK_GRAY}, I think you'll fit in just\nfine.\p"
	.string "If nothing else, I highly doubt\n{COLOR RED}Team Rainbow Rocket {COLOR DARK_GRAY}would suspect\l"
	.string "someone like you.\p"
	.string "Kindly make your way to\n{COLOR RED}Mistralton City{COLOR DARK_GRAY}.\p"
	.string "Ah -- don't worry about accommodation.\nWe've already taken care of that.\p$"

gText_Birch_AreYouReady::
	.string "I'll give you some time to {COLOR BLUE}explore and\nsettle in{COLOR DARK_GRAY}.\p"
	.string "When the time is right, {COLOR RED}Agent Looker\n{COLOR DARK_GRAY}will send for you.\p"
	.string "Until then, just {COLOR BLUE}keep your head down{COLOR DARK_GRAY},\nOK?\p"
	.string "Well, I'll look forward to meeting you in\nperson. Good luck!\p$"
