gText_Birch_Welcome::
	.string "Hello. It's a pleasure to speak to you\nat last.\p"
	.string "My name is {COLOR GREEN}Professor Magnolia{COLOR DARK_GRAY}.\pI'm currently heading up research here\n"
	.string "at {COLOR RED}Unova's Amnesty Institute{COLOR DARK_GRAY}.\p"
	.string "Together, we battle against the forces\nthat have invaded our world.\p"
	.string "Perhaps you're already aware...\p"
	.string "{COLOR RED}Team Rainbow Rocket {COLOR DARK_GRAY}now has\nstrongholds in nine regions, and\l"
	.string "only we remain to oppose them.\p"
	.string "However!\pWhile they have their “secret weapon”,\nin the form of {COLOR RED}Ultra Wormholes{COLOR DARK_GRAY}...\p$"

@ Unused; for some reason this is set in strings.c
gText_Birch_Pokemon::
	.string "$"

gText_Birch_MainSpeech::
	.string "But I'm getting ahead of myself.\p$"

gText_Birch_AndYouAre::
	.string "Now, there's a lot on my plate, so you'll\n"
    .string "have to forgive my rudeness, but...\p$"

gText_Birch_WhatsYourName::
	.string "What did you say your name was, again?$"

gText_Birch_SoItsPlayer::
	.string "“{COLOR GREEN}{PLAYER}{COLOR DARK_GRAY}”...\ndid I get that right?$"

gText_Birch_YourePlayer::
	.string "Well, {COLOR GREEN}{PLAYER}{COLOR DARK_GRAY}, I think you'll fit in just\nfine.\p"
	.string "If nothing else, I highly doubt\n{COLOR RED}Team Rainbow Rocket {COLOR DARK_GRAY}would suspect\l"
	.string "someone as young as you.\p"
	.string "Kindly make your way to\n{COLOR RED}Mistralton City{COLOR DARK_GRAY}.\p"
	.string "Ah -- don't worry about accommodation.\nWe've already taken care of that.\p$"

gText_Birch_AreYouReady::
	.string "I'll give you some time to explore and\nsettle in.\p"
	.string "When the time is right, {COLOR GREEN}Chief Looker\n{COLOR DARK_GRAY}will send for you.\p"
	.string "Until then, just keep your head down,\nOK?\p"
	.string "Well, I'll look forward to meeting you in\nperson. Good luck!\p$"
