gText_ObtainedTheItem::
	.string "I got the {COLOR RED}{STR_VAR_2}{COLOR DARK_GRAY}!$"

gText_TheBagIsFull::
	.string "My {COLOR RED}bag {COLOR DARK_GRAY}is full...$"

gText_PutItemInPocket::
	.string "I put away the {COLOR RED}{STR_VAR_2}{COLOR DARK_GRAY}\n"
	.string "in my {COLOR RED}bag's {STR_VAR_3} pocket{COLOR DARK_GRAY}.$"

gText_PlayerFoundOneItem::
	.string "I found one {COLOR RED}{STR_VAR_2}{COLOR DARK_GRAY}!$"

gText_TooBadBagIsFull::
	.string "Too bad!\n"
	.string "My {COLOR RED}bag{COLOR DARK_GRAY} is full...$"

gText_PlayerPutItemInBag::
	.string "I put away the {COLOR RED}{STR_VAR_2}{COLOR DARK_GRAY}\n"
	.string "in my {COLOR RED}bag{COLOR DARK_GRAY}.$"

gText_ObtainedTheDecor::
	.string "I got the {COLOR RED}{STR_VAR_2}{COLOR DARK_GRAY}!$"

gText_NoRoomLeftForAnother::
	.string "Too bad! There's no room left for\n"
	.string "another {COLOR RED}{STR_VAR_2}{COLOR DARK_GRAY}...$"

gText_TheDecorWasTransferredToThePC::
	.string "The {COLOR RED}{STR_VAR_2} {COLOR DARK_GRAY}was transferred\n"
	.string "to the PC.$"

gText_PlayerFoundItems::
    .string "I found {STR_VAR_1} {COLOR RED}{STR_VAR_2}{COLOR DARK_GRAY}!$"

gText_ObtainedTheItems::
    .string "I got {STR_VAR_1} {COLOR RED}{STR_VAR_2}{COLOR DARK_GRAY}!$"
