gText_ObtainedTheItem::
	.string "You got the {COLOR RED}{SHADOW LIGHT_RED}{STR_VAR_2}{SHADOW LIGHT_GRAY}{COLOR DARK_GRAY}.$"

gText_TheBagIsFull::
	.string "Your bag is full...$"

gText_PutItemInPocket::
	.string "You put away the {COLOR RED}{SHADOW LIGHT_RED}{STR_VAR_2}{SHADOW LIGHT_GRAY}{COLOR DARK_GRAY}\n"
	.string "in your bag's {COLOR RED}{SHADOW LIGHT_RED}{STR_VAR_3}{SHADOW LIGHT_GRAY}{COLOR DARK_GRAY} pocket.$"

gText_PlayerFoundOneItem::
	.string "You found one {COLOR RED}{SHADOW LIGHT_RED}{STR_VAR_2}{SHADOW LIGHT_GRAY}{COLOR DARK_GRAY}.$"

gText_TooBadBagIsFull::
	.string "Too bad! Your bag is full...$"

gText_PlayerPutItemInBag::
	.string "You put away the {COLOR RED}{SHADOW LIGHT_RED}{STR_VAR_2}{SHADOW LIGHT_GRAY}{COLOR DARK_GRAY}\n"
	.string "in your bag.$"

gText_ObtainedTheDecor::
	.string "You got the {COLOR RED}{SHADOW LIGHT_RED}{STR_VAR_2}{SHADOW LIGHT_GRAY}{COLOR DARK_GRAY}!$"

gText_NoRoomLeftForAnother::
	.string "Too bad! There's no room left for\n"
	.string "another {COLOR RED}{SHADOW LIGHT_RED}{STR_VAR_2}{SHADOW LIGHT_GRAY}{COLOR DARK_GRAY}...$"

gText_TheDecorWasTransferredToThePC::
	.string "The {COLOR RED}{SHADOW LIGHT_RED}{STR_VAR_2} {SHADOW LIGHT_GRAY}{COLOR DARK_GRAY}was transferred\n"
	.string "to your PC.$"

gText_PlayerFoundItems::
    .string "You found {STR_VAR_1} {COLOR RED}{SHADOW LIGHT_RED}{STR_VAR_2}{SHADOW LIGHT_GRAY}{COLOR DARK_GRAY}.$"

gText_ObtainedTheItems::
    .string "You got {STR_VAR_1} {COLOR RED}{SHADOW LIGHT_RED}{STR_VAR_2}{SHADOW LIGHT_GRAY}{COLOR DARK_GRAY}.$"
