	.align 2
gText_ConfirmSave::
	.string "Should I update my {COLOR RED}Mission Log{COLOR DARK_GRAY} and save\n"
	.string "my progress?$"

gText_AlreadySavedFile::
	.string "Is it OK to overwrite the existing save\n"
	.string "data?$"

gText_SavingDontTurnOff::
	.string "{COLOR BLUE}Saving... Don't close the emulator.{COLOR DARK_GRAY}$"

gText_PlayerSavedGame::
	.string "My {COLOR RED}Mission Log{COLOR DARK_GRAY} is fully up-to-date!$"

gText_DifferentSaveFile::
	.string "{COLOR BLUE}Warning!\p"
	.string "{COLOR BLUE}There's already a save file belonging to\n"
	.string "{COLOR BLUE}a different adventure.\p"
	.string "{COLOR BLUE}If you save now, the other adventure,\n"
	.string "{COLOR BLUE}including items and Pokémon,\l"
	.string "{COLOR BLUE}will be lost forever.\p"
	.string "{COLOR BLUE}Are you sure you want to overwrite the\n"
	.string "{COLOR BLUE}existing save file?{COLOR DARK_GRAY}$"

gText_SaveError::
	.string "{COLOR BLUE}Sorry, your progress couldn't be saved.\n"
	.string "{COLOR BLUE}Your emulator might not be set up\l"
	.string "{COLOR BLUE}correctly.{COLOR DARK_GRAY}$"

gText_SavingDontTurnOffPower::
	.string "{COLOR BLUE}Saving. Don't close the emulator.{COLOR DARK_GRAY}$"

gText_SavingIShouldWriteSomething::
	.string "I should write something...\n"
	.string "{COLOR BLUE}Saving. Don't close the emulator.{COLOR DARK_GRAY}$"

gText_SavingLetsDoIt::
	.string "Let's do it...\n"
	.string "{COLOR BLUE}Saving. Don't close the emulator.{COLOR DARK_GRAY}$"

gText_SavingIllJustAddThis::
	.string "I'll just add this...\n"
	.string "{COLOR BLUE}Saving. Don't close the emulator.{COLOR DARK_GRAY}$"

gText_SavingNowThen::
	.string "Now then...\n"
	.string "{COLOR BLUE}Saving. Don't close the emulator.{COLOR DARK_GRAY}$"
