	.align 2
gText_ConfirmSave::
	.string "Will you update your {COLOR RED}{SHADOW LIGHT_RED}Mission Log {SHADOW LIGHT_GRAY}{COLOR DARK_GRAY}and\n"
	.string "save your progress?$"

gText_AlreadySavedFile::
	.string "Is it OK to overwrite the existing save\n"
	.string "data?$"

gText_SavingDontTurnOff::
	.string "Saving... Don't close the emulator.$"

gText_PlayerSavedGame::
	.string "Your {COLOR RED}{SHADOW LIGHT_RED}Mission Log {SHADOW LIGHT_GRAY}{COLOR DARK_GRAY}is now up to date.$"

gText_DifferentSaveFile::
	.string "Warning!\p"
	.string "There's already a save file belonging to\n"
	.string "a different adventure.\p"
	.string "If you save now, the other adventure\n"
	.string "will be lost forever.\p"
	.string "That includes all obtained items and\n"
    .string "Pokémon.\p"
	.string "Are you sure you want to overwrite the\n"
	.string "existing save file?$"

gText_SaveError::
	.string "Your adventure couldn't be saved. Your\n"
	.string "emulator might not be set up correctly.$"

gText_SavingDontTurnOffPower::
	.string "Saving... Don't close the emulator.$"

gText_SavingInGameClock::
	.string "By the way...\p"
	.string "You can now adjust the in-game clock\n"
	.string "whenever you want.\p"
	.string "Just press {FONT 14}AB{FONT 11} + {FONT 14}TU{FONT 11} + {FONT 14}W{FONT 11}\n"
	.string "together on the title screen.\p"
	.string "In case you can't remember all that...\p"
	.string "We've added it to the handbook on the\n"
	.string "desk in your house.\p{PAUSE 32}"
	.string "Your {COLOR RED}{SHADOW LIGHT_RED}Mission Log {SHADOW LIGHT_GRAY}{COLOR DARK_GRAY}is now up to date.$"
