	.align 2
gText_ConfirmSave::
	.string "Do you want to save your adventure?$"

gText_AlreadySavedFile::
	.string "There's already a saved adventure.\n"
	.string "Is it OK to overwrite it?$"

gText_SavingDontTurnOff::
	.string "Saving...\n"
	.string "{COLOR BLUE}Don't close the emulator.{COLOR DARK_GRAY}$"

gText_PlayerSavedGame::
	.string "{COLOR DARK_GRAY}Your adventure has been saved.$"

gText_DifferentSaveFile::
	.string "Warning!\p"
	.string "A {COLOR BLUE}different adventure {COLOR DARK_GRAY}has already been\nsaved.\p"
	.string "If you save now, the other adventure,\n"
	.string "including items and Pokémon,\l"
	.string "will be {COLOR BLUE}lost forever{COLOR DARK_GRAY}.\p"
	.string "Are you sure you want to save now and\n"
	.string "overwrite the other adventure?$"

gText_SaveError::
	.string "Sorry, we couldn't save your adventure.\n"
	.string "Your emulator might not be set up\l"
	.string "correctly.$"

gText_SavingDontTurnOffPower::
	.string "Saving...\n"
	.string "{COLOR BLUE}Don't close the emulator.{COLOR DARK_GRAY}$"
